//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WokerzApp.ServiceReferenceWorkerz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="test", ConfigurationName="ServiceReferenceWorkerz.WebServiceWorkerzSoap")]
    public interface WebServiceWorkerzSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="test/GetWorkerDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetWorkerDetails(int peopleID, System.AsyncCallback callback, object asyncState);
        
        WokerzApp.ServiceReferenceWorkerz.WorkerDetailDTO EndGetWorkerDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="test/GetWorkerSkills", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetWorkerSkills(int peopleID, System.AsyncCallback callback, object asyncState);
        
        string EndGetWorkerSkills(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="test/GetWorkerSched", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetWorkerSched(WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedRequest request, System.AsyncCallback callback, object asyncState);
        
        WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedResponse EndGetWorkerSched(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="test/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="test/UserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginUserDetails(System.AsyncCallback callback, object asyncState);
        
        string[] EndUserDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="test/GetCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetCountries(string continent, System.AsyncCallback callback, object asyncState);
        
        string[] EndGetCountries(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="test/GetWorkerzInAndOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetWorkerzInAndOut(System.AsyncCallback callback, object asyncState);
        
        WebWorkerz[] EndGetWorkerzInAndOut(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="test/GetWorkerzAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetWorkerzAll(System.AsyncCallback callback, object asyncState);
        
        WebWorkerz[] EndGetWorkerzAll(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="test")]
    public partial class WorkerDetailDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string skillsField;
        
        private string mondayHoursField;
        
        private string tuesdayHoursField;
        
        private string wednesdayHoursField;
        
        private string thursdayHoursField;
        
        private string fridayHoursField;
        
        private string saturdayHoursField;
        
        private string sundayHoursField;
        
        private string phoneField;
        
        private string emailField;
        
        private string positionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Skills {
            get {
                return this.skillsField;
            }
            set {
                this.skillsField = value;
                this.RaisePropertyChanged("Skills");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MondayHours {
            get {
                return this.mondayHoursField;
            }
            set {
                this.mondayHoursField = value;
                this.RaisePropertyChanged("MondayHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TuesdayHours {
            get {
                return this.tuesdayHoursField;
            }
            set {
                this.tuesdayHoursField = value;
                this.RaisePropertyChanged("TuesdayHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string WednesdayHours {
            get {
                return this.wednesdayHoursField;
            }
            set {
                this.wednesdayHoursField = value;
                this.RaisePropertyChanged("WednesdayHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ThursdayHours {
            get {
                return this.thursdayHoursField;
            }
            set {
                this.thursdayHoursField = value;
                this.RaisePropertyChanged("ThursdayHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FridayHours {
            get {
                return this.fridayHoursField;
            }
            set {
                this.fridayHoursField = value;
                this.RaisePropertyChanged("FridayHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SaturdayHours {
            get {
                return this.saturdayHoursField;
            }
            set {
                this.saturdayHoursField = value;
                this.RaisePropertyChanged("SaturdayHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SundayHours {
            get {
                return this.sundayHoursField;
            }
            set {
                this.sundayHoursField = value;
                this.RaisePropertyChanged("SundayHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="test")]
    public partial class WebWorkerz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool punchedInField;
        
        private int peopleIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string userNameField;
        
        private string workerTypeNameField;
        
        private string locationNameField;
        
        private int locationIDField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime endTimeField;
        
        private string startTimeStringField;
        
        private string endTimeStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool PunchedIn {
            get {
                return this.punchedInField;
            }
            set {
                this.punchedInField = value;
                this.RaisePropertyChanged("PunchedIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PeopleID {
            get {
                return this.peopleIDField;
            }
            set {
                this.peopleIDField = value;
                this.RaisePropertyChanged("PeopleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string WorkerTypeName {
            get {
                return this.workerTypeNameField;
            }
            set {
                this.workerTypeNameField = value;
                this.RaisePropertyChanged("WorkerTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("LocationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int LocationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
                this.RaisePropertyChanged("LocationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StartTimeString {
            get {
                return this.startTimeStringField;
            }
            set {
                this.startTimeStringField = value;
                this.RaisePropertyChanged("StartTimeString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EndTimeString {
            get {
                return this.endTimeStringField;
            }
            set {
                this.endTimeStringField = value;
                this.RaisePropertyChanged("EndTimeString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="test")]
    public partial class WorkerDays : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dayField;
        
        private string startTimeField;
        
        private string endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("Day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkerSched", WrapperNamespace="test", IsWrapped=true)]
    public partial class GetWorkerSchedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="test", Order=0)]
        public int peopleID;
        
        public GetWorkerSchedRequest() {
        }
        
        public GetWorkerSchedRequest(int peopleID) {
            this.peopleID = peopleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWorkerSchedResponse", WrapperNamespace="test", IsWrapped=true)]
    public partial class GetWorkerSchedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="test", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WorkerDays[] GetWorkerSchedResult;
        
        public GetWorkerSchedResponse() {
        }
        
        public GetWorkerSchedResponse(WorkerDays[] GetWorkerSchedResult) {
            this.GetWorkerSchedResult = GetWorkerSchedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceWorkerzSoapChannel : WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WokerzApp.ServiceReferenceWorkerz.WorkerDetailDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WokerzApp.ServiceReferenceWorkerz.WorkerDetailDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkerSkillsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkerSkillsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkerSchedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkerSchedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WorkerDays[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WorkerDays[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCountriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCountriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkerzInAndOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkerzInAndOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebWorkerz[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebWorkerz[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWorkerzAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWorkerzAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WebWorkerz[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WebWorkerz[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceWorkerzSoapClient : System.ServiceModel.ClientBase<WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap>, WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap {
        
        private BeginOperationDelegate onBeginGetWorkerDetailsDelegate;
        
        private EndOperationDelegate onEndGetWorkerDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkerDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWorkerSkillsDelegate;
        
        private EndOperationDelegate onEndGetWorkerSkillsDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkerSkillsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWorkerSchedDelegate;
        
        private EndOperationDelegate onEndGetWorkerSchedDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkerSchedCompletedDelegate;
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginUserDetailsDelegate;
        
        private EndOperationDelegate onEndUserDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onUserDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCountriesDelegate;
        
        private EndOperationDelegate onEndGetCountriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCountriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWorkerzInAndOutDelegate;
        
        private EndOperationDelegate onEndGetWorkerzInAndOutDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkerzInAndOutCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWorkerzAllDelegate;
        
        private EndOperationDelegate onEndGetWorkerzAllDelegate;
        
        private System.Threading.SendOrPostCallback onGetWorkerzAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WebServiceWorkerzSoapClient() {
        }
        
        public WebServiceWorkerzSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceWorkerzSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceWorkerzSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceWorkerzSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetWorkerDetailsCompletedEventArgs> GetWorkerDetailsCompleted;
        
        public event System.EventHandler<GetWorkerSkillsCompletedEventArgs> GetWorkerSkillsCompleted;
        
        public event System.EventHandler<GetWorkerSchedCompletedEventArgs> GetWorkerSchedCompleted;
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<UserDetailsCompletedEventArgs> UserDetailsCompleted;
        
        public event System.EventHandler<GetCountriesCompletedEventArgs> GetCountriesCompleted;
        
        public event System.EventHandler<GetWorkerzInAndOutCompletedEventArgs> GetWorkerzInAndOutCompleted;
        
        public event System.EventHandler<GetWorkerzAllCompletedEventArgs> GetWorkerzAllCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.BeginGetWorkerDetails(int peopleID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkerDetails(peopleID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WokerzApp.ServiceReferenceWorkerz.WorkerDetailDTO WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.EndGetWorkerDetails(System.IAsyncResult result) {
            return base.Channel.EndGetWorkerDetails(result);
        }
        
        private System.IAsyncResult OnBeginGetWorkerDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int peopleID = ((int)(inValues[0]));
            return ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).BeginGetWorkerDetails(peopleID, callback, asyncState);
        }
        
        private object[] OnEndGetWorkerDetails(System.IAsyncResult result) {
            WokerzApp.ServiceReferenceWorkerz.WorkerDetailDTO retVal = ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).EndGetWorkerDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkerDetailsCompleted(object state) {
            if ((this.GetWorkerDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkerDetailsCompleted(this, new GetWorkerDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkerDetailsAsync(int peopleID) {
            this.GetWorkerDetailsAsync(peopleID, null);
        }
        
        public void GetWorkerDetailsAsync(int peopleID, object userState) {
            if ((this.onBeginGetWorkerDetailsDelegate == null)) {
                this.onBeginGetWorkerDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetWorkerDetails);
            }
            if ((this.onEndGetWorkerDetailsDelegate == null)) {
                this.onEndGetWorkerDetailsDelegate = new EndOperationDelegate(this.OnEndGetWorkerDetails);
            }
            if ((this.onGetWorkerDetailsCompletedDelegate == null)) {
                this.onGetWorkerDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkerDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkerDetailsDelegate, new object[] {
                        peopleID}, this.onEndGetWorkerDetailsDelegate, this.onGetWorkerDetailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.BeginGetWorkerSkills(int peopleID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkerSkills(peopleID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.EndGetWorkerSkills(System.IAsyncResult result) {
            return base.Channel.EndGetWorkerSkills(result);
        }
        
        private System.IAsyncResult OnBeginGetWorkerSkills(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int peopleID = ((int)(inValues[0]));
            return ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).BeginGetWorkerSkills(peopleID, callback, asyncState);
        }
        
        private object[] OnEndGetWorkerSkills(System.IAsyncResult result) {
            string retVal = ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).EndGetWorkerSkills(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkerSkillsCompleted(object state) {
            if ((this.GetWorkerSkillsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkerSkillsCompleted(this, new GetWorkerSkillsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkerSkillsAsync(int peopleID) {
            this.GetWorkerSkillsAsync(peopleID, null);
        }
        
        public void GetWorkerSkillsAsync(int peopleID, object userState) {
            if ((this.onBeginGetWorkerSkillsDelegate == null)) {
                this.onBeginGetWorkerSkillsDelegate = new BeginOperationDelegate(this.OnBeginGetWorkerSkills);
            }
            if ((this.onEndGetWorkerSkillsDelegate == null)) {
                this.onEndGetWorkerSkillsDelegate = new EndOperationDelegate(this.OnEndGetWorkerSkills);
            }
            if ((this.onGetWorkerSkillsCompletedDelegate == null)) {
                this.onGetWorkerSkillsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkerSkillsCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkerSkillsDelegate, new object[] {
                        peopleID}, this.onEndGetWorkerSkillsDelegate, this.onGetWorkerSkillsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.BeginGetWorkerSched(WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkerSched(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetWorkerSched(int peopleID, System.AsyncCallback callback, object asyncState) {
            WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedRequest inValue = new WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedRequest();
            inValue.peopleID = peopleID;
            return ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).BeginGetWorkerSched(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedResponse WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.EndGetWorkerSched(System.IAsyncResult result) {
            return base.Channel.EndGetWorkerSched(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private WorkerDays[] EndGetWorkerSched(System.IAsyncResult result) {
            WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedResponse retVal = ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).EndGetWorkerSched(result);
            return retVal.GetWorkerSchedResult;
        }
        
        private System.IAsyncResult OnBeginGetWorkerSched(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int peopleID = ((int)(inValues[0]));
            return this.BeginGetWorkerSched(peopleID, callback, asyncState);
        }
        
        private object[] OnEndGetWorkerSched(System.IAsyncResult result) {
            WorkerDays[] retVal = this.EndGetWorkerSched(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkerSchedCompleted(object state) {
            if ((this.GetWorkerSchedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkerSchedCompleted(this, new GetWorkerSchedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkerSchedAsync(int peopleID) {
            this.GetWorkerSchedAsync(peopleID, null);
        }
        
        public void GetWorkerSchedAsync(int peopleID, object userState) {
            if ((this.onBeginGetWorkerSchedDelegate == null)) {
                this.onBeginGetWorkerSchedDelegate = new BeginOperationDelegate(this.OnBeginGetWorkerSched);
            }
            if ((this.onEndGetWorkerSchedDelegate == null)) {
                this.onEndGetWorkerSchedDelegate = new EndOperationDelegate(this.OnEndGetWorkerSched);
            }
            if ((this.onGetWorkerSchedCompletedDelegate == null)) {
                this.onGetWorkerSchedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkerSchedCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkerSchedDelegate, new object[] {
                        peopleID}, this.onEndGetWorkerSchedDelegate, this.onGetWorkerSchedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.BeginUserDetails(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUserDetails(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.EndUserDetails(System.IAsyncResult result) {
            return base.Channel.EndUserDetails(result);
        }
        
        private System.IAsyncResult OnBeginUserDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).BeginUserDetails(callback, asyncState);
        }
        
        private object[] OnEndUserDetails(System.IAsyncResult result) {
            string[] retVal = ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).EndUserDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUserDetailsCompleted(object state) {
            if ((this.UserDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UserDetailsCompleted(this, new UserDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UserDetailsAsync() {
            this.UserDetailsAsync(null);
        }
        
        public void UserDetailsAsync(object userState) {
            if ((this.onBeginUserDetailsDelegate == null)) {
                this.onBeginUserDetailsDelegate = new BeginOperationDelegate(this.OnBeginUserDetails);
            }
            if ((this.onEndUserDetailsDelegate == null)) {
                this.onEndUserDetailsDelegate = new EndOperationDelegate(this.OnEndUserDetails);
            }
            if ((this.onUserDetailsCompletedDelegate == null)) {
                this.onUserDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUserDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginUserDetailsDelegate, null, this.onEndUserDetailsDelegate, this.onUserDetailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.BeginGetCountries(string continent, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCountries(continent, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.EndGetCountries(System.IAsyncResult result) {
            return base.Channel.EndGetCountries(result);
        }
        
        private System.IAsyncResult OnBeginGetCountries(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string continent = ((string)(inValues[0]));
            return ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).BeginGetCountries(continent, callback, asyncState);
        }
        
        private object[] OnEndGetCountries(System.IAsyncResult result) {
            string[] retVal = ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).EndGetCountries(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCountriesCompleted(object state) {
            if ((this.GetCountriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCountriesCompleted(this, new GetCountriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCountriesAsync(string continent) {
            this.GetCountriesAsync(continent, null);
        }
        
        public void GetCountriesAsync(string continent, object userState) {
            if ((this.onBeginGetCountriesDelegate == null)) {
                this.onBeginGetCountriesDelegate = new BeginOperationDelegate(this.OnBeginGetCountries);
            }
            if ((this.onEndGetCountriesDelegate == null)) {
                this.onEndGetCountriesDelegate = new EndOperationDelegate(this.OnEndGetCountries);
            }
            if ((this.onGetCountriesCompletedDelegate == null)) {
                this.onGetCountriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCountriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCountriesDelegate, new object[] {
                        continent}, this.onEndGetCountriesDelegate, this.onGetCountriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.BeginGetWorkerzInAndOut(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkerzInAndOut(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebWorkerz[] WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.EndGetWorkerzInAndOut(System.IAsyncResult result) {
            return base.Channel.EndGetWorkerzInAndOut(result);
        }
        
        private System.IAsyncResult OnBeginGetWorkerzInAndOut(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).BeginGetWorkerzInAndOut(callback, asyncState);
        }
        
        private object[] OnEndGetWorkerzInAndOut(System.IAsyncResult result) {
            WebWorkerz[] retVal = ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).EndGetWorkerzInAndOut(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkerzInAndOutCompleted(object state) {
            if ((this.GetWorkerzInAndOutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkerzInAndOutCompleted(this, new GetWorkerzInAndOutCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkerzInAndOutAsync() {
            this.GetWorkerzInAndOutAsync(null);
        }
        
        public void GetWorkerzInAndOutAsync(object userState) {
            if ((this.onBeginGetWorkerzInAndOutDelegate == null)) {
                this.onBeginGetWorkerzInAndOutDelegate = new BeginOperationDelegate(this.OnBeginGetWorkerzInAndOut);
            }
            if ((this.onEndGetWorkerzInAndOutDelegate == null)) {
                this.onEndGetWorkerzInAndOutDelegate = new EndOperationDelegate(this.OnEndGetWorkerzInAndOut);
            }
            if ((this.onGetWorkerzInAndOutCompletedDelegate == null)) {
                this.onGetWorkerzInAndOutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkerzInAndOutCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkerzInAndOutDelegate, null, this.onEndGetWorkerzInAndOutDelegate, this.onGetWorkerzInAndOutCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.BeginGetWorkerzAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWorkerzAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebWorkerz[] WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap.EndGetWorkerzAll(System.IAsyncResult result) {
            return base.Channel.EndGetWorkerzAll(result);
        }
        
        private System.IAsyncResult OnBeginGetWorkerzAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).BeginGetWorkerzAll(callback, asyncState);
        }
        
        private object[] OnEndGetWorkerzAll(System.IAsyncResult result) {
            WebWorkerz[] retVal = ((WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap)(this)).EndGetWorkerzAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWorkerzAllCompleted(object state) {
            if ((this.GetWorkerzAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWorkerzAllCompleted(this, new GetWorkerzAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWorkerzAllAsync() {
            this.GetWorkerzAllAsync(null);
        }
        
        public void GetWorkerzAllAsync(object userState) {
            if ((this.onBeginGetWorkerzAllDelegate == null)) {
                this.onBeginGetWorkerzAllDelegate = new BeginOperationDelegate(this.OnBeginGetWorkerzAll);
            }
            if ((this.onEndGetWorkerzAllDelegate == null)) {
                this.onEndGetWorkerzAllDelegate = new EndOperationDelegate(this.OnEndGetWorkerzAll);
            }
            if ((this.onGetWorkerzAllCompletedDelegate == null)) {
                this.onGetWorkerzAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWorkerzAllCompleted);
            }
            base.InvokeAsync(this.onBeginGetWorkerzAllDelegate, null, this.onEndGetWorkerzAllDelegate, this.onGetWorkerzAllCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap CreateChannel() {
            return new WebServiceWorkerzSoapClientChannel(this);
        }
        
        private class WebServiceWorkerzSoapClientChannel : ChannelBase<WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap>, WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap {
            
            public WebServiceWorkerzSoapClientChannel(System.ServiceModel.ClientBase<WokerzApp.ServiceReferenceWorkerz.WebServiceWorkerzSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetWorkerDetails(int peopleID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = peopleID;
                System.IAsyncResult _result = base.BeginInvoke("GetWorkerDetails", _args, callback, asyncState);
                return _result;
            }
            
            public WokerzApp.ServiceReferenceWorkerz.WorkerDetailDTO EndGetWorkerDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                WokerzApp.ServiceReferenceWorkerz.WorkerDetailDTO _result = ((WokerzApp.ServiceReferenceWorkerz.WorkerDetailDTO)(base.EndInvoke("GetWorkerDetails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWorkerSkills(int peopleID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = peopleID;
                System.IAsyncResult _result = base.BeginInvoke("GetWorkerSkills", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetWorkerSkills(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetWorkerSkills", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWorkerSched(WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetWorkerSched", _args, callback, asyncState);
                return _result;
            }
            
            public WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedResponse EndGetWorkerSched(System.IAsyncResult result) {
                object[] _args = new object[0];
                WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedResponse _result = ((WokerzApp.ServiceReferenceWorkerz.GetWorkerSchedResponse)(base.EndInvoke("GetWorkerSched", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUserDetails(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("UserDetails", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndUserDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("UserDetails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCountries(string continent, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = continent;
                System.IAsyncResult _result = base.BeginInvoke("GetCountries", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndGetCountries(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("GetCountries", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWorkerzInAndOut(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetWorkerzInAndOut", _args, callback, asyncState);
                return _result;
            }
            
            public WebWorkerz[] EndGetWorkerzInAndOut(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebWorkerz[] _result = ((WebWorkerz[])(base.EndInvoke("GetWorkerzInAndOut", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWorkerzAll(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetWorkerzAll", _args, callback, asyncState);
                return _result;
            }
            
            public WebWorkerz[] EndGetWorkerzAll(System.IAsyncResult result) {
                object[] _args = new object[0];
                WebWorkerz[] _result = ((WebWorkerz[])(base.EndInvoke("GetWorkerzAll", _args, result)));
                return _result;
            }
        }
    }
}
